import { corsHeaders, validCollectorId } from "../_store";

export function GET(request: Request) {
  const url = new URL(request.url); const id = url.searchParams.get("id") ?? "";
  if (!validCollectorId(id)) return new Response("console.error('TARS Inspector: invalid collector id')", { status: 400, headers: { ...corsHeaders, "Content-Type": "application/javascript; charset=utf-8" } });
  const endpoint = `${url.origin}/api/collector/snapshot?id=${encodeURIComponent(id)}`;
  const source = `(()=>{const endpoint=${JSON.stringify(endpoint)};const number=v=>{const n=parseFloat(v);return Number.isFinite(n)?Math.round(n*100)/100:null};const text=e=>Array.from(e.childNodes).filter(n=>n.nodeType===3).map(n=>n.textContent||'').join(' ').replace(/\\s+/g,' ').trim();const capture=()=>{const elements=[];for(const e of document.body.querySelectorAll('*')){if(elements.length>=500)break;const value=text(e);if(!value)continue;const r=e.getBoundingClientRect();const s=getComputedStyle(e);if(r.width<=0||r.height<=0||s.display==='none'||s.visibility==='hidden'||Number(s.opacity)===0)continue;elements.push({text:value,tag:e.tagName.toLowerCase(),fontFamily:s.fontFamily,fontWeight:number(s.fontWeight),fontSize:number(s.fontSize),lineHeight:s.lineHeight==='normal'?null:number(s.lineHeight),letterSpacing:s.letterSpacing==='normal'?0:number(s.letterSpacing),color:s.color,x:Math.round((r.left+scrollX)*100)/100,y:Math.round((r.top+scrollY)*100)/100,width:Math.round(r.width*100)/100,height:Math.round(r.height*100)/100})}fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:location.href,title:document.title,viewportWidth:innerWidth,viewportHeight:innerHeight,pageWidth:document.documentElement.scrollWidth,pageHeight:document.documentElement.scrollHeight,elements})}).then(()=>console.info('TARS UI Inspector: 已采集 '+elements.length+' 个文字元素')).catch(error=>console.error('TARS UI Inspector: 采集失败',error))};let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(capture,500)};document.readyState==='loading'?addEventListener('DOMContentLoaded',capture,{once:true}):capture();addEventListener('resize',schedule);window.TARS_UI_INSPECTOR_CAPTURE=capture})();`;
  return new Response(source, { headers: { ...corsHeaders, "Content-Type": "application/javascript; charset=utf-8" } });
}
